# Generated by Django 5.0.4 on 2024-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('WK', 'Work'), ('ST', 'Study'), ('PR', 'Personal')], default='PR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
